apiVersion: s3.chedaws.io/v1
kind: Namespace
metadata:
  name: vpn-gis
  owner: oms-reporting
  description: Landing area for VPN GIS data delivered through GSA
spec:
  producer:
    environments:
      dev:
        certificateSubject:
          - "CN=COVWEDC2GSAD01.corp.chedha.net"
      test:
        certificateSubject:
          - "CN=COVWEDC2GSAD01.corp.chedha.net"
